### ISSUE TITLE
Firebase Modify: Dynamic Childpath not set properly

### ISSUE THREAD

**Issue by aaronfranco** [deldrid1/node-red-contrib-firebase#2]
According to the Node's information, in order to use the "msg.childpath" property, the "childpath" field in the Node's configuration must be left blank. Unfortunately, this is incorrect. In order to use the "msg.childpath" property to set the childpath dynamically, the "childpath" field in the Node's configuration must be set to "msg.childpath." Otherwise, the childpath will be automatically set to the root of the database.

See line 167 in firebase_modify.js

```
//Parse out msg.childpath
          var childpath = this.childpath
          if(childpath == "msg.childpath"){  // <--- Here is the issue
            if("childpath" in msg){
              childpath = msg.childpath
            }
          }
```

**Comment by deldrid1** [comment]
Are you sure you're using the latest version of the nodes?  And this version of the firebase nodes (there are a few out there)?

Originally the plan was to leave msg.childpath blank but it was decided that a more explicit option would be better.  My version of the nodes has msg.childpath as an autocomplete option and the documentation looks up to date as well...

<img width="1222" alt="screenshot 2015-12-14 08 23 18" src="https://cloud.githubusercontent.com/assets/583660/11781986/f7a93262-a23b-11e5-92da-3cb96109c911.png">

**Comment by aaronfranco** [comment]
I'm on version 0.1.2 pulled from NPM. 
Installed with

```
npm install node-red-contrib-firebase --save
```

I don't see what you see. 
Node-red version is 0.12.4

**Comment by deldrid1** [comment]
I think this may have been an npm publishing issue.. (Sorry, I don't maintain many public packages)

I've bumped the version and republished - can you try 0.1.3 and see if it is cleared up?

**Comment by aaronfranco** [comment]
fixed :+1:
