### ISSUE TITLE
Does auth work at all?

### ISSUE THREAD

**Issue by rm-rf-etc** [deldrid1/node-red-contrib-firebase#25]
The only auth setting that works for me is "None". I can't find any examples online for using this node with auth, and any setting that I try results in "AUTHENTICATION_DISABLED" errors. I would think that basic email login credentials should work, but the result is the same.

**Comment by deldrid1** [comment]
See PR #17 - the code isn't rock solid yet, but @ssoleman has most of the basic functionality working (as well as a number of new features)

As for why the nodes are "broken", these nodes were made before Firebase was fully integrated into GCP, at which point they overhauled auth completely. 

For "legacy" firebase instances, the older auth strategies are still functional. Unfortunately, for new Firebase's, these nodes are borderline useless and you need to use @ssolemon's branch until I pull it in.

**Comment by rm-rf-etc** [comment]
What do you think about implementing another node which uses the firebase-admin module? After downloading and installing the credentials, you'll have a secure connection. For servers this is a good solution (but not for devices).

**Comment by deldrid1** [comment]
Take a look at https://github.com/ssoleman/node-red-contrib-firebase/blob/master/firebase/firebase_config.js - its making use of both the client and the admin SDK as it makes sense :)

If you'd like to contribute, I'd encourage you to contribute to all of the work @ssoleman has done.
