### ISSUE TITLE
Node-Red crashes except on Mac

### ISSUE THREAD

**Issue by rajendran20** [deldrid1/node-red-contrib-firebase#32]
Hi I am trying to use this node for my project and when I tried it on windows, node red crashes (server disconnected issue) and the node-red exits to the command prompt. The same issue happens on pi3 (after doing all the upgrade), this time the log shows exiting code on "failed with result signal". But when I tried it on Mac, there is no issue at all. As for windows and pi3, node-red is ok until I deploy this node.
This is without any form of authentication

**Comment by deldrid1** [comment]
See #28...
