### ISSUE TITLE
Node.js: Server-side JavaScript has stopped working | node-red

### ISSUE THREAD

**Issue by sahebdatta** [deldrid1/node-red-contrib-firebase#33]
Hello everyone,

I'm trying to run node-red on windows 10. whenever I try to fire-up node-red from cmd, I get a pop-up with the following error, "Node.js: Server-side JavaScript has stopped working". It wasn't the same always. Previously, node-red was working just fine on the same windows 10 device. I tried to use the firebase.on() node (node-red-contrib-firebase) to fetch data from firebase. It is after then I am getting this error. I tried to restart my PC, uninstall and re-install node-red and node.js, nothing worked. The same node works just fine on my Raspberry Pi. Kindly help me solve this issue.

Thanks in advance

**Comment by sahebdatta** [comment]
So I did a bit of trial and error and found out that it's the node-red-contrib-firebase pallet is creating the issue. Whenever I am trying to provide the credentials to any of the nodes and deploy it, the error pops up and node-red stops after a few seconds. It again starts working when I delete the credential and the node from the flow and deploy it.


![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/9/5/95aa05081f49d6bb7333bdadcfd8b3f1238b3b9c.png)

![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/d/2/d212e1602e7d4780d5f787bd9ac8086ef5e6be93.png)

![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/f/9/f9ef8ce1f47c12f58149210e5f94ec9d395a3199.png)

![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/6/7/67b5434b7ed9c6c106ea6087bcc608c588ea6036.png)

![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/4/c/4c2082d98f43ff2062bdce15e9bfc35f1b5dfb3d.png)

**Comment by deldrid1** [comment]
See the README. 

https://github.com/deldrid1/node-red-contrib-firebase/issues/28 - unfortunately, this repo is no longer maintained and is known to not work with the latest versions of node-red / Firebase.  Perhaps you can take up the cause - if you are up to the challenge and want to submit a complete PR or a new repo that wants to take this npm package name, please submit a PR or File a Pull Request and I will be happy to review
